spring.application.name=cep-api

spring.profiles.active=prod

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT-3

spring.h2.console.path=/h2-console

server.port=${PORT:8080}